/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CategorySlugChooseGenderRouteImport } from './routes/category.$slug.choose-gender'
import { Route as CategorySlugGenderRouteImport } from './routes/category.$slug.$gender'
import { Route as ApiPublicNotifyNewReportRouteImport } from './routes/api/public/notify-new-report'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedListingIdManageRouteImport } from './routes/_authenticated/listing.$id.manage'

const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugChooseGenderRoute =
  CategorySlugChooseGenderRouteImport.update({
    id: '/category/$slug/choose-gender',
    path: '/category/$slug/choose-gender',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategorySlugGenderRoute = CategorySlugGenderRouteImport.update({
  id: '/category/$slug/$gender',
  path: '/category/$slug/$gender',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyNewReportRoute =
  ApiPublicNotifyNewReportRouteImport.update({
    id: '/api/public/notify-new-report',
    path: '/api/public/notify-new-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingIdManageRoute =
  AuthenticatedListingIdManageRouteImport.update({
    id: '/listing/$id/manage',
    path: '/listing/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/user/$id': typeof UserIdRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/api/public/notify-new-report': typeof ApiPublicNotifyNewReportRoute
  '/category/$slug/$gender': typeof CategorySlugGenderRoute
  '/category/$slug/choose-gender': typeof CategorySlugChooseGenderRoute
  '/listing/$id/manage': typeof AuthenticatedListingIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/user/$id': typeof UserIdRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/api/public/notify-new-report': typeof ApiPublicNotifyNewReportRoute
  '/category/$slug/$gender': typeof CategorySlugGenderRoute
  '/category/$slug/choose-gender': typeof CategorySlugChooseGenderRoute
  '/listing/$id/manage': typeof AuthenticatedListingIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/user/$id': typeof UserIdRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/api/public/notify-new-report': typeof ApiPublicNotifyNewReportRoute
  '/category/$slug/$gender': typeof CategorySlugGenderRoute
  '/category/$slug/choose-gender': typeof CategorySlugChooseGenderRoute
  '/_authenticated/listing/$id/manage': typeof AuthenticatedListingIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/profile'
    | '/product/$id'
    | '/user/$id'
    | '/admin/reports'
    | '/api/public/notify-new-report'
    | '/category/$slug/$gender'
    | '/category/$slug/choose-gender'
    | '/listing/$id/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/profile'
    | '/product/$id'
    | '/user/$id'
    | '/admin/reports'
    | '/api/public/notify-new-report'
    | '/category/$slug/$gender'
    | '/category/$slug/choose-gender'
    | '/listing/$id/manage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/_authenticated/profile'
    | '/product/$id'
    | '/user/$id'
    | '/_authenticated/admin/reports'
    | '/api/public/notify-new-report'
    | '/category/$slug/$gender'
    | '/category/$slug/choose-gender'
    | '/_authenticated/listing/$id/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  ProductIdRoute: typeof ProductIdRoute
  UserIdRoute: typeof UserIdRoute
  ApiPublicNotifyNewReportRoute: typeof ApiPublicNotifyNewReportRoute
  CategorySlugGenderRoute: typeof CategorySlugGenderRoute
  CategorySlugChooseGenderRoute: typeof CategorySlugChooseGenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug/choose-gender': {
      id: '/category/$slug/choose-gender'
      path: '/category/$slug/choose-gender'
      fullPath: '/category/$slug/choose-gender'
      preLoaderRoute: typeof CategorySlugChooseGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$gender': {
      id: '/category/$slug/$gender'
      path: '/category/$slug/$gender'
      fullPath: '/category/$slug/$gender'
      preLoaderRoute: typeof CategorySlugGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-new-report': {
      id: '/api/public/notify-new-report'
      path: '/api/public/notify-new-report'
      fullPath: '/api/public/notify-new-report'
      preLoaderRoute: typeof ApiPublicNotifyNewReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing/$id/manage': {
      id: '/_authenticated/listing/$id/manage'
      path: '/listing/$id/manage'
      fullPath: '/listing/$id/manage'
      preLoaderRoute: typeof AuthenticatedListingIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedListingIdManageRoute: typeof AuthenticatedListingIdManageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedListingIdManageRoute: AuthenticatedListingIdManageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  ProductIdRoute: ProductIdRoute,
  UserIdRoute: UserIdRoute,
  ApiPublicNotifyNewReportRoute: ApiPublicNotifyNewReportRoute,
  CategorySlugGenderRoute: CategorySlugGenderRoute,
  CategorySlugChooseGenderRoute: CategorySlugChooseGenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
