/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthSignupFullRouteImport } from './routes/auth.signup-full'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth.confirm-email'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMyPromotionsRouteImport } from './routes/_authenticated/my-promotions'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as UserIdIndexRouteImport } from './routes/user.$id.index'
import { Route as UserIdFollowingRouteImport } from './routes/user.$id.following'
import { Route as UserIdFollowersRouteImport } from './routes/user.$id.followers'
import { Route as CategorySlugSubcategoryRouteImport } from './routes/category.$slug.subcategory'
import { Route as CategorySlugChooseGenderRouteImport } from './routes/category.$slug.choose-gender'
import { Route as CategorySlugGenderRouteImport } from './routes/category.$slug.$gender'
import { Route as ApiPublicNotifyPendingPromotionRouteImport } from './routes/api/public/notify-pending-promotion'
import { Route as ApiPublicNotifyNewReportRouteImport } from './routes/api/public/notify-new-report'
import { Route as AuthenticatedProfileDeleteAccountRouteImport } from './routes/_authenticated/profile_.delete-account'
import { Route as AuthenticatedProfileChangeEmailRouteImport } from './routes/_authenticated/profile_.change-email'
import { Route as AuthenticatedBuyIdRouteImport } from './routes/_authenticated/buy.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin.promotions'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedListingIdPromoteRouteImport } from './routes/_authenticated/listing.$id.promote'
import { Route as AuthenticatedListingIdPremiumRouteImport } from './routes/_authenticated/listing.$id.premium'
import { Route as AuthenticatedListingIdManageRouteImport } from './routes/_authenticated/listing.$id.manage'
import { Route as AuthenticatedListingIdEditRouteImport } from './routes/_authenticated/listing.$id.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupFullRoute = AuthSignupFullRouteImport.update({
  id: '/signup-full',
  path: '/signup-full',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPromotionsRoute =
  AuthenticatedMyPromotionsRouteImport.update({
    id: '/my-promotions',
    path: '/my-promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdFollowingRoute = UserIdFollowingRouteImport.update({
  id: '/user/$id/following',
  path: '/user/$id/following',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdFollowersRoute = UserIdFollowersRouteImport.update({
  id: '/user/$id/followers',
  path: '/user/$id/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugSubcategoryRoute = CategorySlugSubcategoryRouteImport.update({
  id: '/category/$slug/subcategory',
  path: '/category/$slug/subcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugChooseGenderRoute =
  CategorySlugChooseGenderRouteImport.update({
    id: '/category/$slug/choose-gender',
    path: '/category/$slug/choose-gender',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategorySlugGenderRoute = CategorySlugGenderRouteImport.update({
  id: '/category/$slug/$gender',
  path: '/category/$slug/$gender',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyPendingPromotionRoute =
  ApiPublicNotifyPendingPromotionRouteImport.update({
    id: '/api/public/notify-pending-promotion',
    path: '/api/public/notify-pending-promotion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotifyNewReportRoute =
  ApiPublicNotifyNewReportRouteImport.update({
    id: '/api/public/notify-new-report',
    path: '/api/public/notify-new-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileDeleteAccountRoute =
  AuthenticatedProfileDeleteAccountRouteImport.update({
    id: '/profile_/delete-account',
    path: '/profile/delete-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileChangeEmailRoute =
  AuthenticatedProfileChangeEmailRouteImport.update({
    id: '/profile_/change-email',
    path: '/profile/change-email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyIdRoute = AuthenticatedBuyIdRouteImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/admin/promotions',
    path: '/admin/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListingIdPromoteRoute =
  AuthenticatedListingIdPromoteRouteImport.update({
    id: '/listing/$id/promote',
    path: '/listing/$id/promote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingIdPremiumRoute =
  AuthenticatedListingIdPremiumRouteImport.update({
    id: '/listing/$id/premium',
    path: '/listing/$id/premium',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingIdManageRoute =
  AuthenticatedListingIdManageRouteImport.update({
    id: '/listing/$id/manage',
    path: '/listing/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingIdEditRoute =
  AuthenticatedListingIdEditRouteImport.update({
    id: '/listing/$id/edit',
    path: '/listing/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/favorites': typeof FavoritesRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/my-promotions': typeof AuthenticatedMyPromotionsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup-full': typeof AuthSignupFullRoute
  '/product/$id': typeof ProductIdRoute
  '/auth/': typeof AuthIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/buy/$id': typeof AuthenticatedBuyIdRoute
  '/profile/change-email': typeof AuthenticatedProfileChangeEmailRoute
  '/profile/delete-account': typeof AuthenticatedProfileDeleteAccountRoute
  '/api/public/notify-new-report': typeof ApiPublicNotifyNewReportRoute
  '/api/public/notify-pending-promotion': typeof ApiPublicNotifyPendingPromotionRoute
  '/category/$slug/$gender': typeof CategorySlugGenderRoute
  '/category/$slug/choose-gender': typeof CategorySlugChooseGenderRoute
  '/category/$slug/subcategory': typeof CategorySlugSubcategoryRoute
  '/user/$id/followers': typeof UserIdFollowersRoute
  '/user/$id/following': typeof UserIdFollowingRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/listing/$id/edit': typeof AuthenticatedListingIdEditRoute
  '/listing/$id/manage': typeof AuthenticatedListingIdManageRoute
  '/listing/$id/premium': typeof AuthenticatedListingIdPremiumRoute
  '/listing/$id/promote': typeof AuthenticatedListingIdPromoteRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/favorites': typeof FavoritesRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/my-promotions': typeof AuthenticatedMyPromotionsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup-full': typeof AuthSignupFullRoute
  '/product/$id': typeof ProductIdRoute
  '/auth': typeof AuthIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/buy/$id': typeof AuthenticatedBuyIdRoute
  '/profile/change-email': typeof AuthenticatedProfileChangeEmailRoute
  '/profile/delete-account': typeof AuthenticatedProfileDeleteAccountRoute
  '/api/public/notify-new-report': typeof ApiPublicNotifyNewReportRoute
  '/api/public/notify-pending-promotion': typeof ApiPublicNotifyPendingPromotionRoute
  '/category/$slug/$gender': typeof CategorySlugGenderRoute
  '/category/$slug/choose-gender': typeof CategorySlugChooseGenderRoute
  '/category/$slug/subcategory': typeof CategorySlugSubcategoryRoute
  '/user/$id/followers': typeof UserIdFollowersRoute
  '/user/$id/following': typeof UserIdFollowingRoute
  '/user/$id': typeof UserIdIndexRoute
  '/listing/$id/edit': typeof AuthenticatedListingIdEditRoute
  '/listing/$id/manage': typeof AuthenticatedListingIdManageRoute
  '/listing/$id/premium': typeof AuthenticatedListingIdPremiumRoute
  '/listing/$id/promote': typeof AuthenticatedListingIdPromoteRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/favorites': typeof FavoritesRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/my-promotions': typeof AuthenticatedMyPromotionsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup-full': typeof AuthSignupFullRoute
  '/product/$id': typeof ProductIdRoute
  '/auth/': typeof AuthIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/buy/$id': typeof AuthenticatedBuyIdRoute
  '/_authenticated/profile_/change-email': typeof AuthenticatedProfileChangeEmailRoute
  '/_authenticated/profile_/delete-account': typeof AuthenticatedProfileDeleteAccountRoute
  '/api/public/notify-new-report': typeof ApiPublicNotifyNewReportRoute
  '/api/public/notify-pending-promotion': typeof ApiPublicNotifyPendingPromotionRoute
  '/category/$slug/$gender': typeof CategorySlugGenderRoute
  '/category/$slug/choose-gender': typeof CategorySlugChooseGenderRoute
  '/category/$slug/subcategory': typeof CategorySlugSubcategoryRoute
  '/user/$id/followers': typeof UserIdFollowersRoute
  '/user/$id/following': typeof UserIdFollowingRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/_authenticated/listing/$id/edit': typeof AuthenticatedListingIdEditRoute
  '/_authenticated/listing/$id/manage': typeof AuthenticatedListingIdManageRoute
  '/_authenticated/listing/$id/premium': typeof AuthenticatedListingIdPremiumRoute
  '/_authenticated/listing/$id/promote': typeof AuthenticatedListingIdPromoteRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blocked'
    | '/favorites'
    | '/mcp'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/terms'
    | '/users'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/membership'
    | '/my-promotions'
    | '/onboarding'
    | '/profile'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup-full'
    | '/product/$id'
    | '/auth/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/users'
    | '/buy/$id'
    | '/profile/change-email'
    | '/profile/delete-account'
    | '/api/public/notify-new-report'
    | '/api/public/notify-pending-promotion'
    | '/category/$slug/$gender'
    | '/category/$slug/choose-gender'
    | '/category/$slug/subcategory'
    | '/user/$id/followers'
    | '/user/$id/following'
    | '/user/$id/'
    | '/listing/$id/edit'
    | '/listing/$id/manage'
    | '/listing/$id/premium'
    | '/listing/$id/promote'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/favorites'
    | '/mcp'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/terms'
    | '/users'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/membership'
    | '/my-promotions'
    | '/onboarding'
    | '/profile'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup-full'
    | '/product/$id'
    | '/auth'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/users'
    | '/buy/$id'
    | '/profile/change-email'
    | '/profile/delete-account'
    | '/api/public/notify-new-report'
    | '/api/public/notify-pending-promotion'
    | '/category/$slug/$gender'
    | '/category/$slug/choose-gender'
    | '/category/$slug/subcategory'
    | '/user/$id/followers'
    | '/user/$id/following'
    | '/user/$id'
    | '/listing/$id/edit'
    | '/listing/$id/manage'
    | '/listing/$id/premium'
    | '/listing/$id/promote'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blocked'
    | '/favorites'
    | '/mcp'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/terms'
    | '/users'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/membership'
    | '/_authenticated/my-promotions'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup-full'
    | '/product/$id'
    | '/auth/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/buy/$id'
    | '/_authenticated/profile_/change-email'
    | '/_authenticated/profile_/delete-account'
    | '/api/public/notify-new-report'
    | '/api/public/notify-pending-promotion'
    | '/category/$slug/$gender'
    | '/category/$slug/choose-gender'
    | '/category/$slug/subcategory'
    | '/user/$id/followers'
    | '/user/$id/following'
    | '/user/$id/'
    | '/_authenticated/listing/$id/edit'
    | '/_authenticated/listing/$id/manage'
    | '/_authenticated/listing/$id/premium'
    | '/_authenticated/listing/$id/promote'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlockedRoute: typeof BlockedRoute
  FavoritesRoute: typeof FavoritesRoute
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
  UsersRoute: typeof UsersRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProductIdRoute: typeof ProductIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicNotifyNewReportRoute: typeof ApiPublicNotifyNewReportRoute
  ApiPublicNotifyPendingPromotionRoute: typeof ApiPublicNotifyPendingPromotionRoute
  CategorySlugGenderRoute: typeof CategorySlugGenderRoute
  CategorySlugChooseGenderRoute: typeof CategorySlugChooseGenderRoute
  CategorySlugSubcategoryRoute: typeof CategorySlugSubcategoryRoute
  UserIdFollowersRoute: typeof UserIdFollowersRoute
  UserIdFollowingRoute: typeof UserIdFollowingRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup-full': {
      id: '/auth/signup-full'
      path: '/signup-full'
      fullPath: '/auth/signup-full'
      preLoaderRoute: typeof AuthSignupFullRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-promotions': {
      id: '/_authenticated/my-promotions'
      path: '/my-promotions'
      fullPath: '/my-promotions'
      preLoaderRoute: typeof AuthenticatedMyPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/following': {
      id: '/user/$id/following'
      path: '/user/$id/following'
      fullPath: '/user/$id/following'
      preLoaderRoute: typeof UserIdFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/followers': {
      id: '/user/$id/followers'
      path: '/user/$id/followers'
      fullPath: '/user/$id/followers'
      preLoaderRoute: typeof UserIdFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/subcategory': {
      id: '/category/$slug/subcategory'
      path: '/category/$slug/subcategory'
      fullPath: '/category/$slug/subcategory'
      preLoaderRoute: typeof CategorySlugSubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/choose-gender': {
      id: '/category/$slug/choose-gender'
      path: '/category/$slug/choose-gender'
      fullPath: '/category/$slug/choose-gender'
      preLoaderRoute: typeof CategorySlugChooseGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$gender': {
      id: '/category/$slug/$gender'
      path: '/category/$slug/$gender'
      fullPath: '/category/$slug/$gender'
      preLoaderRoute: typeof CategorySlugGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-pending-promotion': {
      id: '/api/public/notify-pending-promotion'
      path: '/api/public/notify-pending-promotion'
      fullPath: '/api/public/notify-pending-promotion'
      preLoaderRoute: typeof ApiPublicNotifyPendingPromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-new-report': {
      id: '/api/public/notify-new-report'
      path: '/api/public/notify-new-report'
      fullPath: '/api/public/notify-new-report'
      preLoaderRoute: typeof ApiPublicNotifyNewReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile_/delete-account': {
      id: '/_authenticated/profile_/delete-account'
      path: '/profile/delete-account'
      fullPath: '/profile/delete-account'
      preLoaderRoute: typeof AuthenticatedProfileDeleteAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/change-email': {
      id: '/_authenticated/profile_/change-email'
      path: '/profile/change-email'
      fullPath: '/profile/change-email'
      preLoaderRoute: typeof AuthenticatedProfileChangeEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy/$id': {
      id: '/_authenticated/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof AuthenticatedBuyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/listing/$id/promote': {
      id: '/_authenticated/listing/$id/promote'
      path: '/listing/$id/promote'
      fullPath: '/listing/$id/promote'
      preLoaderRoute: typeof AuthenticatedListingIdPromoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing/$id/premium': {
      id: '/_authenticated/listing/$id/premium'
      path: '/listing/$id/premium'
      fullPath: '/listing/$id/premium'
      preLoaderRoute: typeof AuthenticatedListingIdPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing/$id/manage': {
      id: '/_authenticated/listing/$id/manage'
      path: '/listing/$id/manage'
      fullPath: '/listing/$id/manage'
      preLoaderRoute: typeof AuthenticatedListingIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing/$id/edit': {
      id: '/_authenticated/listing/$id/edit'
      path: '/listing/$id/edit'
      fullPath: '/listing/$id/edit'
      preLoaderRoute: typeof AuthenticatedListingIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedMyPromotionsRoute: typeof AuthenticatedMyPromotionsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBuyIdRoute: typeof AuthenticatedBuyIdRoute
  AuthenticatedProfileChangeEmailRoute: typeof AuthenticatedProfileChangeEmailRoute
  AuthenticatedProfileDeleteAccountRoute: typeof AuthenticatedProfileDeleteAccountRoute
  AuthenticatedListingIdEditRoute: typeof AuthenticatedListingIdEditRoute
  AuthenticatedListingIdManageRoute: typeof AuthenticatedListingIdManageRoute
  AuthenticatedListingIdPremiumRoute: typeof AuthenticatedListingIdPremiumRoute
  AuthenticatedListingIdPromoteRoute: typeof AuthenticatedListingIdPromoteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedMyPromotionsRoute: AuthenticatedMyPromotionsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBuyIdRoute: AuthenticatedBuyIdRoute,
  AuthenticatedProfileChangeEmailRoute: AuthenticatedProfileChangeEmailRoute,
  AuthenticatedProfileDeleteAccountRoute:
    AuthenticatedProfileDeleteAccountRoute,
  AuthenticatedListingIdEditRoute: AuthenticatedListingIdEditRoute,
  AuthenticatedListingIdManageRoute: AuthenticatedListingIdManageRoute,
  AuthenticatedListingIdPremiumRoute: AuthenticatedListingIdPremiumRoute,
  AuthenticatedListingIdPromoteRoute: AuthenticatedListingIdPromoteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupFullRoute: typeof AuthSignupFullRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupFullRoute: AuthSignupFullRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlockedRoute: BlockedRoute,
  FavoritesRoute: FavoritesRoute,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
  UsersRoute: UsersRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProductIdRoute: ProductIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicNotifyNewReportRoute: ApiPublicNotifyNewReportRoute,
  ApiPublicNotifyPendingPromotionRoute: ApiPublicNotifyPendingPromotionRoute,
  CategorySlugGenderRoute: CategorySlugGenderRoute,
  CategorySlugChooseGenderRoute: CategorySlugChooseGenderRoute,
  CategorySlugSubcategoryRoute: CategorySlugSubcategoryRoute,
  UserIdFollowersRoute: UserIdFollowersRoute,
  UserIdFollowingRoute: UserIdFollowingRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
